### ISSUE TITLE
Passwords not encrypted in config files and not obfuscated in web GUI

### ISSUE THREAD

**Issue by jacob-hudson** [damiendallimore/SplunkModularInputsPythonFramework#21]
Passwords are currently being exposed on our Linux servers and in the Web GUI when using the app

Maybe check out what other apps, such as DB connect and the slack addon are each doing for password management!

Thanks in advance, let me know what I can do to help!

**Comment by damiendallimore** [comment]
Correct, very aware of how to create encrypted credentials , done it countless times , and we perform customizations for our customers that have commercial support contracts with us.
